### ISSUE TITLE
Card's don't scale on small screen (iPhone 4)

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#78] opened 2016-12-17 17:42 UTC
- Can't see flood information
- Can't progress after photo page
<img width="319" alt="screen shot 2016-12-17 at 11 40 26 am" src="https://cloud.githubusercontent.com/assets/944642/21288619/35090b68-c456-11e6-97d9-e585e9d8ac28.png">
<img width="318" alt="screen shot 2016-12-17 at 11 40 33 am" src="https://cloud.githubusercontent.com/assets/944642/21288621/370944e6-c456-11e6-95d8-14e832023083.png">

**Comment by matthewberryman** [comment] 2017-01-05 04:55
There's also a size issue on the iPhone 6 (regular size)—see attached image. I'm placing it here rather than opening another issue as it all seems part of general layout issues on different-sized screens that needs to be fixed on multiple pages of a card. 
![img_2432](https://cloud.githubusercontent.com/assets/2288238/21669370/4801e4de-d35f-11e6-8c11-45b5974c798c.PNG)

**Comment by talltom** [comment] 2017-01-05 16:01
Confirmed on:
- iPhone 6 (iOS 10.2, Safari 10) [XCode emulator]

**Comment by talltom** [comment] 2017-01-09 16:08
This is currently working on:
- iPhone 6 (iOS 10.2, Safari 10) [XCode emulator]
- iPhone 6 (iOS 10.1, Safari 10) [Physical device]

**Comment by ojha-url** [comment] 2017-01-09 23:22
Scaling issue requires additional media query in css for screen sizes less than 340p. (iphone 4 & below).

On large screen sizes, mostly iOS as noted above, the hidden slider glitch seems to be caused by the following:
- delayed load of roboto font's font.css file
- i18n polyfill

**Closed** 2017-01-11 07:09 UTC
Labels: bug
