### ISSUE TITLE
Review translation and UI text

### ISSUE THREAD

**Issue by talltom** [urbanriskmap/petabencana.id#127] opened 2017-01-12 19:40 UTC
1) Review language used in cards (buttons, hints, titles etc., and user notifications via bot)
2) review Indonesian translation of card items

**Comment by prittandrani** [comment] 2017-01-13 03:39
Hi all, some suggestion from me:

In Telegram Bot:
- Reply from /start: "Hi! Saya BencanaBot. Ketik /banjir untuk melaporkan banjir."
- Translation of /banjir (when you hit the forward slash icon in the typing box): "laporkan banjir"
- Reply from /banjir: "Hi! Laporkan menggunakan link ini. Terima kasih." 

Minor issue: from Telegram Bot, when I type /banjir the card language is ID, but with /flood it is also ID (if it can be changed to EN would be great).

In Cards: EN is all good. For translations:
- Next --- "Lanjutkan" (now it is 'Terus')
- Swipe to Submit --- "Geser" (now it is 'Gesek')

cc @fadmastuti please check also.

**Comment by matthewberryman** [comment] 2017-01-13 09:37
I will work on this list in the middle of the night Jkt time tonight (other stuff currently taking priority before then).  If you have anything to add, feel free. If there's stuff after I work on it and close it, then re-open it.

**Comment by talltom** [comment] 2017-01-13 15:34
Hi @prittandrani I've started crossing out your issues as I fixed them.

Regarding this issue,

> Minor issue: from Telegram Bot, when I type /banjir the card language is ID, but with /flood it is also ID (if it can be changed to EN would be great).

It should have replied in English (/flood) or Indonesian (/banjir) so I'm not sure what's going on here. I am unable to recreate this, the bot replies to me in the correct language. This may have been something in the default language setting for the bot.

@matthewberryman translation fixes are over in the telegram master branch. I have **not** deployed these. https://github.com/urbanriskmap/cognicity-reports-telegram/commit/005a8889b85cba451532b67a493ed3019001d16e

**Comment by talltom** [comment] 2017-01-13 15:45
@matthewberryman - translation fixes for card buttons are in https://github.com/urbanriskmap/petabencana.id/commit/0d71e4d40b570afa4f180f6ac9116ae20988928c on /dev branch. I have *not* merged to master for deployment as it is still evening in Jakarta.

**Comment by talltom** [comment] 2017-01-13 15:58
Suggest we leave this issue open until all is deployed.

**Comment by matthewberryman** [comment] 2017-01-13 21:27
@talltom I can't deploy this independently as planned as you've done it, because you put these changes into dev along with other work; I will create a separate branch with just your single commit and pull request that to merge.

**Comment by matthewberryman** [comment] 2017-01-13 22:18
@talltom @prittandrani deployed petabencana.id and telegram changes and confirmed default language for telegram (and twitter) bots is ID, and I am getting the right language back for /banjir and /flood with telegram.

**Comment by prittandrani** [comment] 2017-01-13 23:49
@matthewberryman ok I am getting the right language for Telegram. Thanks.

@talltom thanks for crossing out, one thing left on the cards translation:
- on the Review & Submit card: "Description or Photo required to submit report" -- "Deskripsi atau Foto diperlukan untuk melapor"
(Now it is "deskripsi foto wajib menyampaikan laporan"

I only can mention you because I am not able to reopen this regarding that last translation.

**Closed** 2017-01-14 04:04 UTC
Labels: enhancement

**Comment by matthewberryman** [comment] 2017-01-14 04:07
@prittandrani reopened and fixed
